export default {
  ID: /^[A-Za-z0-9]{1,50}$/,
  PW: /^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[!@#$%^&*()\-_=+\[\]{}|;:'",.<>?/])[A-Za-z\d!@#$%^&*()\-_=+\[\]{}|;:'",.<>?/]{8,32}$/,
  NICKNAME: /^[가-힣a-zA-Z0-9]{1,50}$/,
  CODE: /^[0-9]{6}$/,
  EMAIL: /^[A-Za-z0-9.+\-_]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/,
  INDEX: /^\d+$/,
  COORDINATE: /^-?\d+(\.\d+)?$/,
  RANGE: /^\d+$/,
  PAGE: /^\d+$/,
  RESTAURANT_NAME:
    /^[A-Za-z가-힣0-9!@#$%^&*()_+\[\]{}|\\;:'",.<>/?`~\- ]{1,15}$/,
  ADDRESS: /^[가-힣a-zA-Z0-9\s\-]+(로|길)\s?\d{1,4}(-\d{1,4})?$/,
  ADDRESS_DETAIL: /^[가-힣a-zA-Z0-9\s\-#.,]{1,100}$/,
  RESTAURANT_PHONE: /^(01[016789]\d{8}|0\d{1,2}\d{7,8}|1[5-6]\d{2}\d{4})$/,
  RESTAURANT_RUN_TIME: /^\d{4}$/,
  BOOLEAN: /^(true|false)$/,
  CATEGORY_NAME: /^.{1,10}$/,
  REVIEW: /^.{1,200}$/,
  MENU_NAME: /^.{1,20}$/,
  MENU_PRICE: /^\d+$/,
};
